language: go

go:
  - 1.9

sudo: required

services:
  - docker

before_install:
  - cp config/aws_credentials.example config/aws_credentials
  - docker build -t wolfbeacon-infra-ops .

script:
  - go version